# Generated by Django 4.2.2 on 2023-07-29 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learner', '0002_alter_school_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='passcode',
            field=models.CharField(default='vb56QS', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
