# Generated by Django 4.2.2 on 2023-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_alter_school_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='passcode',
            field=models.CharField(default='66431C4D0679', max_length=12, unique=True),
        ),
    ]
