# Generated by Django 4.2.2 on 2023-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_alter_school_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='passcode',
            field=models.CharField(default='E6C23B0EEEA0', max_length=12),
        ),
    ]
