# Generated by Django 4.2.2 on 2023-07-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_alter_school_passcode_alter_school_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learner.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='passcode',
            field=models.CharField(default='6QIPsd', max_length=8, unique=True),
        ),
    ]
